name: Auditing
on:
  - push
jobs:
  rubocop:
    name: Audit bundler
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3
          bundler-cache: true

      - name: Run Bundler Audit
        run: bundle exec bundler-audit
