name: Tests
on:
  - push
jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3
          bundler-cache: true
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock # Required to use SSH key from the previous step of adding SSH key

      - name: Run RSpec
        run: bundle exec rspec
        env:
          RAILS_ENV: test

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage

  coverage:
    runs-on: ubuntu-latest
    needs: rspec
    name: Test coverage

    steps:
    - name: Download coverage report
      uses: actions/download-artifact@v2
      with:
        name: coverage-report
        path: coverage

    - name: Enforce test coverage
      uses: vigetlabs/simplecov-check@1.0
      with:
        minimum_coverage: 100
        coverage_path: coverage/.last_run.json
